### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by ebob9** [fuzzz/extshark#2]
Did you intend to release this code and not allow anyone to modify or redistribute it? Since you didn't specify a license, that's currently the case - https://help.github.com/articles/open-source-licensing/#what-happens-if-i-dont-choose-a-license

If that was not your intent, can you add a LICENSE file and let us know how we can use your code? Thanks!

**Comment by fuzzz** [comment]
Hello, Aaron!

Just added MIT Licence. Do anything you want :)

**Comment by ebob9** [comment]
Awesome, thanks a bunch!
