### ISSUE TITLE
How to install this on centos?

### ISSUE THREAD

**Issue by colokcabut** [fuzzz/extshark#3]
Hi,

How to install this on centos?

Thank you,
colokcabut

**Comment by fuzzz** [comment]
Just install apache, php, perl, tshark. And put extshark files to www directory.

**Comment by colokcabut** [comment]
Hi,

Already put the extshark to www, but when i open it on my browser i got blank page.
Any idea what i'm doing wrong?

Best Regards

**Comment by fuzzz** [comment]
There an error in symlink
/extshark/lib/ext
Just make it relative to your path.
I will correct it later.

**Comment by fuzzz** [comment]
Just remove that useless linking.
So you could now try clonning again

**Comment by colokcabut** [comment]
Hi,

It works now. ^^
Thank you.

**Comment by fuzzz** [comment]
Great!
I have a plan to rewrite backend to nodejs and to add some capture functionality... If i will have enough time for that plan :)
