### ISSUE TITLE
Do not open pcap files

### ISSUE THREAD

**Issue by ghost** [fuzzz/extshark#4]
Hello, Mikhail!
I deployed your application on Linux Debian x86_64. Pre-installed apache2, php5, perl and tshark. When I try to open a pcap file, nothing happens in the interface. In the log file /var/log/apache2/error.log an error message appears:
[Tue May 24 14:17:57 2016] [error] [client 192.168.14.50] PHP Warning:  filesize(): stat failed for /var/www/extshark/php/../data/tmp/dumps/20-05-2016_19-45.pcap/view_.csv in /var/www/extshark/php/classes/TShark.php on line 46, referer: http://172.16.117.12/extshark/
Please tell me how to fix it?

Best regards!
Alexander

**Comment by fuzzz** [comment]
Hi!
That interface do not completed at all, it could open file, could show each packet detailed info. But it quite buggy and was used by me to open really large pcap without downloading. So if you do not afraid of some debugging you will launch it :)

First of all, please check existing of file "/data/tmp/dumps/20-05-2016_19-45.pcap/view_.csv"
This file was created by calling perl script at https://github.com/fuzzz/extshark/blob/master/php/classes/TShark.php#L35
For debugging you can try to run that script with same arguments manually.(There are no error handling :) )

**Comment by ghost** [comment]
Mikhail!
Thank you very much for your answer! After viewing the do_psml.pl script I found the cause of the error. Do not automatically installed package libhtml-parser-perl. The pcap file is now displayed in the web interface. Sorry to disturb.
Good luck in your developments!
Alexander

**Comment by fuzzz** [comment]
feel free to bother me if something goes wrong again :) GL

**Comment by ghost** [comment]
OK :)
Thank you very much!
